// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/mihon/backup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateStrategy int32

const (
	UpdateStrategy_ALWAYS_UPDATE   UpdateStrategy = 0
	UpdateStrategy_ONLY_FETCH_ONCE UpdateStrategy = 1
)

// Enum value maps for UpdateStrategy.
var (
	UpdateStrategy_name = map[int32]string{
		0: "ALWAYS_UPDATE",
		1: "ONLY_FETCH_ONCE",
	}
	UpdateStrategy_value = map[string]int32{
		"ALWAYS_UPDATE":   0,
		"ONLY_FETCH_ONCE": 1,
	}
)

func (x UpdateStrategy) Enum() *UpdateStrategy {
	p := new(UpdateStrategy)
	*p = x
	return p
}

func (x UpdateStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mihon_backup_proto_enumTypes[0].Descriptor()
}

func (UpdateStrategy) Type() protoreflect.EnumType {
	return &file_proto_mihon_backup_proto_enumTypes[0]
}

func (x UpdateStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UpdateStrategy) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UpdateStrategy(num)
	return nil
}

// Deprecated: Use UpdateStrategy.Descriptor instead.
func (UpdateStrategy) EnumDescriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{0}
}

type PreferenceValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Truevalue     []byte                 `protobuf:"bytes,2,req,name=truevalue" json:"truevalue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreferenceValue) Reset() {
	*x = PreferenceValue{}
	mi := &file_proto_mihon_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferenceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferenceValue) ProtoMessage() {}

func (x *PreferenceValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferenceValue.ProtoReflect.Descriptor instead.
func (*PreferenceValue) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{0}
}

func (x *PreferenceValue) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *PreferenceValue) GetTruevalue() []byte {
	if x != nil {
		return x.Truevalue
	}
	return nil
}

// Main backup message
type Backup struct {
	state                   protoimpl.MessageState     `protogen:"open.v1"`
	BackupManga             []*BackupManga             `protobuf:"bytes,1,rep,name=backupManga" json:"backupManga,omitempty"`
	BackupCategories        []*BackupCategory          `protobuf:"bytes,2,rep,name=backupCategories" json:"backupCategories,omitempty"`
	BackupSources           []*BackupSource            `protobuf:"bytes,101,rep,name=backupSources" json:"backupSources,omitempty"`
	BackupPreferences       []*BackupPreference        `protobuf:"bytes,104,rep,name=backupPreferences" json:"backupPreferences,omitempty"`
	BackupSourcePreferences []*BackupSourcePreferences `protobuf:"bytes,105,rep,name=backupSourcePreferences" json:"backupSourcePreferences,omitempty"`
	BackupExtensionRepo     []*BackupExtensionRepos    `protobuf:"bytes,106,rep,name=backupExtensionRepo" json:"backupExtensionRepo,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Backup) Reset() {
	*x = Backup{}
	mi := &file_proto_mihon_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backup) ProtoMessage() {}

func (x *Backup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backup.ProtoReflect.Descriptor instead.
func (*Backup) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{1}
}

func (x *Backup) GetBackupManga() []*BackupManga {
	if x != nil {
		return x.BackupManga
	}
	return nil
}

func (x *Backup) GetBackupCategories() []*BackupCategory {
	if x != nil {
		return x.BackupCategories
	}
	return nil
}

func (x *Backup) GetBackupSources() []*BackupSource {
	if x != nil {
		return x.BackupSources
	}
	return nil
}

func (x *Backup) GetBackupPreferences() []*BackupPreference {
	if x != nil {
		return x.BackupPreferences
	}
	return nil
}

func (x *Backup) GetBackupSourcePreferences() []*BackupSourcePreferences {
	if x != nil {
		return x.BackupSourcePreferences
	}
	return nil
}

func (x *Backup) GetBackupExtensionRepo() []*BackupExtensionRepos {
	if x != nil {
		return x.BackupExtensionRepo
	}
	return nil
}

type BackupCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Order         *int64                 `protobuf:"varint,2,opt,name=order" json:"order,omitempty"`
	Id            *int64                 `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	Flags         *int64                 `protobuf:"varint,100,opt,name=flags" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupCategory) Reset() {
	*x = BackupCategory{}
	mi := &file_proto_mihon_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupCategory) ProtoMessage() {}

func (x *BackupCategory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupCategory.ProtoReflect.Descriptor instead.
func (*BackupCategory) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{2}
}

func (x *BackupCategory) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *BackupCategory) GetOrder() int64 {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return 0
}

func (x *BackupCategory) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *BackupCategory) GetFlags() int64 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

type BackupChapter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Url            *string                `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	Name           *string                `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Scanlator      *string                `protobuf:"bytes,3,opt,name=scanlator" json:"scanlator,omitempty"`
	Read           *bool                  `protobuf:"varint,4,opt,name=read" json:"read,omitempty"`
	Bookmark       *bool                  `protobuf:"varint,5,opt,name=bookmark" json:"bookmark,omitempty"`
	LastPageRead   *int64                 `protobuf:"varint,6,opt,name=lastPageRead" json:"lastPageRead,omitempty"`
	DateFetch      *int64                 `protobuf:"varint,7,opt,name=dateFetch" json:"dateFetch,omitempty"`
	DateUpload     *int64                 `protobuf:"varint,8,opt,name=dateUpload" json:"dateUpload,omitempty"`
	ChapterNumber  *float32               `protobuf:"fixed32,9,opt,name=chapterNumber" json:"chapterNumber,omitempty"`
	SourceOrder    *int64                 `protobuf:"varint,10,opt,name=sourceOrder" json:"sourceOrder,omitempty"`
	LastModifiedAt *int64                 `protobuf:"varint,11,opt,name=lastModifiedAt" json:"lastModifiedAt,omitempty"`
	Version        *int64                 `protobuf:"varint,12,opt,name=version" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackupChapter) Reset() {
	*x = BackupChapter{}
	mi := &file_proto_mihon_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupChapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupChapter) ProtoMessage() {}

func (x *BackupChapter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupChapter.ProtoReflect.Descriptor instead.
func (*BackupChapter) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{3}
}

func (x *BackupChapter) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *BackupChapter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *BackupChapter) GetScanlator() string {
	if x != nil && x.Scanlator != nil {
		return *x.Scanlator
	}
	return ""
}

func (x *BackupChapter) GetRead() bool {
	if x != nil && x.Read != nil {
		return *x.Read
	}
	return false
}

func (x *BackupChapter) GetBookmark() bool {
	if x != nil && x.Bookmark != nil {
		return *x.Bookmark
	}
	return false
}

func (x *BackupChapter) GetLastPageRead() int64 {
	if x != nil && x.LastPageRead != nil {
		return *x.LastPageRead
	}
	return 0
}

func (x *BackupChapter) GetDateFetch() int64 {
	if x != nil && x.DateFetch != nil {
		return *x.DateFetch
	}
	return 0
}

func (x *BackupChapter) GetDateUpload() int64 {
	if x != nil && x.DateUpload != nil {
		return *x.DateUpload
	}
	return 0
}

func (x *BackupChapter) GetChapterNumber() float32 {
	if x != nil && x.ChapterNumber != nil {
		return *x.ChapterNumber
	}
	return 0
}

func (x *BackupChapter) GetSourceOrder() int64 {
	if x != nil && x.SourceOrder != nil {
		return *x.SourceOrder
	}
	return 0
}

func (x *BackupChapter) GetLastModifiedAt() int64 {
	if x != nil && x.LastModifiedAt != nil {
		return *x.LastModifiedAt
	}
	return 0
}

func (x *BackupChapter) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type BackupExtensionRepos struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl               *string                `protobuf:"bytes,1,req,name=baseUrl" json:"baseUrl,omitempty"`
	Name                  *string                `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	ShortName             *string                `protobuf:"bytes,3,opt,name=shortName" json:"shortName,omitempty"`
	Website               *string                `protobuf:"bytes,4,req,name=website" json:"website,omitempty"`
	SigningKeyFingerprint *string                `protobuf:"bytes,5,req,name=signingKeyFingerprint" json:"signingKeyFingerprint,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BackupExtensionRepos) Reset() {
	*x = BackupExtensionRepos{}
	mi := &file_proto_mihon_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupExtensionRepos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupExtensionRepos) ProtoMessage() {}

func (x *BackupExtensionRepos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupExtensionRepos.ProtoReflect.Descriptor instead.
func (*BackupExtensionRepos) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{4}
}

func (x *BackupExtensionRepos) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return ""
}

func (x *BackupExtensionRepos) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *BackupExtensionRepos) GetShortName() string {
	if x != nil && x.ShortName != nil {
		return *x.ShortName
	}
	return ""
}

func (x *BackupExtensionRepos) GetWebsite() string {
	if x != nil && x.Website != nil {
		return *x.Website
	}
	return ""
}

func (x *BackupExtensionRepos) GetSigningKeyFingerprint() string {
	if x != nil && x.SigningKeyFingerprint != nil {
		return *x.SigningKeyFingerprint
	}
	return ""
}

type BackupHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	LastRead      *int64                 `protobuf:"varint,2,req,name=lastRead" json:"lastRead,omitempty"`
	ReadDuration  *int64                 `protobuf:"varint,3,opt,name=readDuration" json:"readDuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupHistory) Reset() {
	*x = BackupHistory{}
	mi := &file_proto_mihon_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupHistory) ProtoMessage() {}

func (x *BackupHistory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupHistory.ProtoReflect.Descriptor instead.
func (*BackupHistory) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{5}
}

func (x *BackupHistory) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *BackupHistory) GetLastRead() int64 {
	if x != nil && x.LastRead != nil {
		return *x.LastRead
	}
	return 0
}

func (x *BackupHistory) GetReadDuration() int64 {
	if x != nil && x.ReadDuration != nil {
		return *x.ReadDuration
	}
	return 0
}

type BackupManga struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Source             *int64                 `protobuf:"varint,1,req,name=source" json:"source,omitempty"`
	Url                *string                `protobuf:"bytes,2,req,name=url" json:"url,omitempty"`
	Title              *string                `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Artist             *string                `protobuf:"bytes,4,opt,name=artist" json:"artist,omitempty"`
	Author             *string                `protobuf:"bytes,5,opt,name=author" json:"author,omitempty"`
	Description        *string                `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	Genre              []string               `protobuf:"bytes,7,rep,name=genre" json:"genre,omitempty"`
	Status             *int32                 `protobuf:"varint,8,opt,name=status" json:"status,omitempty"`
	ThumbnailUrl       *string                `protobuf:"bytes,9,opt,name=thumbnailUrl" json:"thumbnailUrl,omitempty"`
	DateAdded          *int64                 `protobuf:"varint,13,opt,name=dateAdded" json:"dateAdded,omitempty"`
	Viewer             *int32                 `protobuf:"varint,14,opt,name=viewer" json:"viewer,omitempty"`
	Chapters           []*BackupChapter       `protobuf:"bytes,16,rep,name=chapters" json:"chapters,omitempty"`
	Categories         []int64                `protobuf:"varint,17,rep,name=categories" json:"categories,omitempty"`
	Tracking           []*BackupTracking      `protobuf:"bytes,18,rep,name=tracking" json:"tracking,omitempty"`
	Favorite           *bool                  `protobuf:"varint,100,opt,name=favorite" json:"favorite,omitempty"`
	ChapterFlags       *int32                 `protobuf:"varint,101,opt,name=chapterFlags" json:"chapterFlags,omitempty"`
	ViewerFlags        *int32                 `protobuf:"varint,103,opt,name=viewer_flags,json=viewerFlags" json:"viewer_flags,omitempty"`
	History            []*BackupHistory       `protobuf:"bytes,104,rep,name=history" json:"history,omitempty"`
	UpdateStrategy     *UpdateStrategy        `protobuf:"varint,105,opt,name=updateStrategy,enum=mihon.backup.UpdateStrategy" json:"updateStrategy,omitempty"`
	LastModifiedAt     *int64                 `protobuf:"varint,106,opt,name=lastModifiedAt" json:"lastModifiedAt,omitempty"`
	FavoriteModifiedAt *int64                 `protobuf:"varint,107,opt,name=favoriteModifiedAt" json:"favoriteModifiedAt,omitempty"`
	ExcludedScanlators []string               `protobuf:"bytes,108,rep,name=excludedScanlators" json:"excludedScanlators,omitempty"`
	Version            *int64                 `protobuf:"varint,109,opt,name=version" json:"version,omitempty"`
	Notes              *string                `protobuf:"bytes,110,opt,name=notes" json:"notes,omitempty"`
	Initialized        *bool                  `protobuf:"varint,111,opt,name=initialized" json:"initialized,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BackupManga) Reset() {
	*x = BackupManga{}
	mi := &file_proto_mihon_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupManga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupManga) ProtoMessage() {}

func (x *BackupManga) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupManga.ProtoReflect.Descriptor instead.
func (*BackupManga) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{6}
}

func (x *BackupManga) GetSource() int64 {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return 0
}

func (x *BackupManga) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *BackupManga) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *BackupManga) GetArtist() string {
	if x != nil && x.Artist != nil {
		return *x.Artist
	}
	return ""
}

func (x *BackupManga) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *BackupManga) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *BackupManga) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *BackupManga) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *BackupManga) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *BackupManga) GetDateAdded() int64 {
	if x != nil && x.DateAdded != nil {
		return *x.DateAdded
	}
	return 0
}

func (x *BackupManga) GetViewer() int32 {
	if x != nil && x.Viewer != nil {
		return *x.Viewer
	}
	return 0
}

func (x *BackupManga) GetChapters() []*BackupChapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *BackupManga) GetCategories() []int64 {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *BackupManga) GetTracking() []*BackupTracking {
	if x != nil {
		return x.Tracking
	}
	return nil
}

func (x *BackupManga) GetFavorite() bool {
	if x != nil && x.Favorite != nil {
		return *x.Favorite
	}
	return false
}

func (x *BackupManga) GetChapterFlags() int32 {
	if x != nil && x.ChapterFlags != nil {
		return *x.ChapterFlags
	}
	return 0
}

func (x *BackupManga) GetViewerFlags() int32 {
	if x != nil && x.ViewerFlags != nil {
		return *x.ViewerFlags
	}
	return 0
}

func (x *BackupManga) GetHistory() []*BackupHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *BackupManga) GetUpdateStrategy() UpdateStrategy {
	if x != nil && x.UpdateStrategy != nil {
		return *x.UpdateStrategy
	}
	return UpdateStrategy_ALWAYS_UPDATE
}

func (x *BackupManga) GetLastModifiedAt() int64 {
	if x != nil && x.LastModifiedAt != nil {
		return *x.LastModifiedAt
	}
	return 0
}

func (x *BackupManga) GetFavoriteModifiedAt() int64 {
	if x != nil && x.FavoriteModifiedAt != nil {
		return *x.FavoriteModifiedAt
	}
	return 0
}

func (x *BackupManga) GetExcludedScanlators() []string {
	if x != nil {
		return x.ExcludedScanlators
	}
	return nil
}

func (x *BackupManga) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *BackupManga) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *BackupManga) GetInitialized() bool {
	if x != nil && x.Initialized != nil {
		return *x.Initialized
	}
	return false
}

type BackupPreference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value         *PreferenceValue       `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupPreference) Reset() {
	*x = BackupPreference{}
	mi := &file_proto_mihon_backup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupPreference) ProtoMessage() {}

func (x *BackupPreference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupPreference.ProtoReflect.Descriptor instead.
func (*BackupPreference) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{7}
}

func (x *BackupPreference) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *BackupPreference) GetValue() *PreferenceValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type BackupSourcePreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceKey     *string                `protobuf:"bytes,1,req,name=sourceKey" json:"sourceKey,omitempty"`
	Prefs         []*BackupPreference    `protobuf:"bytes,2,rep,name=prefs" json:"prefs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSourcePreferences) Reset() {
	*x = BackupSourcePreferences{}
	mi := &file_proto_mihon_backup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSourcePreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSourcePreferences) ProtoMessage() {}

func (x *BackupSourcePreferences) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSourcePreferences.ProtoReflect.Descriptor instead.
func (*BackupSourcePreferences) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{8}
}

func (x *BackupSourcePreferences) GetSourceKey() string {
	if x != nil && x.SourceKey != nil {
		return *x.SourceKey
	}
	return ""
}

func (x *BackupSourcePreferences) GetPrefs() []*BackupPreference {
	if x != nil {
		return x.Prefs
	}
	return nil
}

type IntPreferenceValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *int32                 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntPreferenceValue) Reset() {
	*x = IntPreferenceValue{}
	mi := &file_proto_mihon_backup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntPreferenceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntPreferenceValue) ProtoMessage() {}

func (x *IntPreferenceValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntPreferenceValue.ProtoReflect.Descriptor instead.
func (*IntPreferenceValue) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{9}
}

func (x *IntPreferenceValue) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type LongPreferenceValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *int64                 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongPreferenceValue) Reset() {
	*x = LongPreferenceValue{}
	mi := &file_proto_mihon_backup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongPreferenceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongPreferenceValue) ProtoMessage() {}

func (x *LongPreferenceValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongPreferenceValue.ProtoReflect.Descriptor instead.
func (*LongPreferenceValue) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{10}
}

func (x *LongPreferenceValue) GetValue() int64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type FloatPreferenceValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *float32               `protobuf:"fixed32,1,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatPreferenceValue) Reset() {
	*x = FloatPreferenceValue{}
	mi := &file_proto_mihon_backup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatPreferenceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatPreferenceValue) ProtoMessage() {}

func (x *FloatPreferenceValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatPreferenceValue.ProtoReflect.Descriptor instead.
func (*FloatPreferenceValue) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{11}
}

func (x *FloatPreferenceValue) GetValue() float32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type StringPreferenceValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringPreferenceValue) Reset() {
	*x = StringPreferenceValue{}
	mi := &file_proto_mihon_backup_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringPreferenceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringPreferenceValue) ProtoMessage() {}

func (x *StringPreferenceValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringPreferenceValue.ProtoReflect.Descriptor instead.
func (*StringPreferenceValue) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{12}
}

func (x *StringPreferenceValue) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type BooleanPreferenceValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *bool                  `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanPreferenceValue) Reset() {
	*x = BooleanPreferenceValue{}
	mi := &file_proto_mihon_backup_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanPreferenceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanPreferenceValue) ProtoMessage() {}

func (x *BooleanPreferenceValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanPreferenceValue.ProtoReflect.Descriptor instead.
func (*BooleanPreferenceValue) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{13}
}

func (x *BooleanPreferenceValue) GetValue() bool {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return false
}

type StringSetPreferenceValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []string               `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringSetPreferenceValue) Reset() {
	*x = StringSetPreferenceValue{}
	mi := &file_proto_mihon_backup_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringSetPreferenceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringSetPreferenceValue) ProtoMessage() {}

func (x *StringSetPreferenceValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringSetPreferenceValue.ProtoReflect.Descriptor instead.
func (*StringSetPreferenceValue) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{14}
}

func (x *StringSetPreferenceValue) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type BackupSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	SourceId      *int64                 `protobuf:"varint,2,req,name=sourceId" json:"sourceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSource) Reset() {
	*x = BackupSource{}
	mi := &file_proto_mihon_backup_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSource) ProtoMessage() {}

func (x *BackupSource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSource.ProtoReflect.Descriptor instead.
func (*BackupSource) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{15}
}

func (x *BackupSource) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *BackupSource) GetSourceId() int64 {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return 0
}

type BackupTracking struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SyncId              *int32                 `protobuf:"varint,1,req,name=syncId" json:"syncId,omitempty"`
	LibraryId           *int64                 `protobuf:"varint,2,req,name=libraryId" json:"libraryId,omitempty"`
	MediaIdInt          *int32                 `protobuf:"varint,3,opt,name=mediaIdInt" json:"mediaIdInt,omitempty"`
	TrackingUrl         *string                `protobuf:"bytes,4,opt,name=trackingUrl" json:"trackingUrl,omitempty"`
	Title               *string                `protobuf:"bytes,5,opt,name=title" json:"title,omitempty"`
	LastChapterRead     *float32               `protobuf:"fixed32,6,opt,name=lastChapterRead" json:"lastChapterRead,omitempty"`
	TotalChapters       *int32                 `protobuf:"varint,7,opt,name=totalChapters" json:"totalChapters,omitempty"`
	Score               *float32               `protobuf:"fixed32,8,opt,name=score" json:"score,omitempty"`
	Status              *int32                 `protobuf:"varint,9,opt,name=status" json:"status,omitempty"`
	StartedReadingDate  *int64                 `protobuf:"varint,10,opt,name=startedReadingDate" json:"startedReadingDate,omitempty"`
	FinishedReadingDate *int64                 `protobuf:"varint,11,opt,name=finishedReadingDate" json:"finishedReadingDate,omitempty"`
	Private             *bool                  `protobuf:"varint,12,opt,name=private" json:"private,omitempty"`
	MediaId             *int64                 `protobuf:"varint,100,opt,name=mediaId" json:"mediaId,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BackupTracking) Reset() {
	*x = BackupTracking{}
	mi := &file_proto_mihon_backup_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupTracking) ProtoMessage() {}

func (x *BackupTracking) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupTracking.ProtoReflect.Descriptor instead.
func (*BackupTracking) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{16}
}

func (x *BackupTracking) GetSyncId() int32 {
	if x != nil && x.SyncId != nil {
		return *x.SyncId
	}
	return 0
}

func (x *BackupTracking) GetLibraryId() int64 {
	if x != nil && x.LibraryId != nil {
		return *x.LibraryId
	}
	return 0
}

func (x *BackupTracking) GetMediaIdInt() int32 {
	if x != nil && x.MediaIdInt != nil {
		return *x.MediaIdInt
	}
	return 0
}

func (x *BackupTracking) GetTrackingUrl() string {
	if x != nil && x.TrackingUrl != nil {
		return *x.TrackingUrl
	}
	return ""
}

func (x *BackupTracking) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *BackupTracking) GetLastChapterRead() float32 {
	if x != nil && x.LastChapterRead != nil {
		return *x.LastChapterRead
	}
	return 0
}

func (x *BackupTracking) GetTotalChapters() int32 {
	if x != nil && x.TotalChapters != nil {
		return *x.TotalChapters
	}
	return 0
}

func (x *BackupTracking) GetScore() float32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *BackupTracking) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *BackupTracking) GetStartedReadingDate() int64 {
	if x != nil && x.StartedReadingDate != nil {
		return *x.StartedReadingDate
	}
	return 0
}

func (x *BackupTracking) GetFinishedReadingDate() int64 {
	if x != nil && x.FinishedReadingDate != nil {
		return *x.FinishedReadingDate
	}
	return 0
}

func (x *BackupTracking) GetPrivate() bool {
	if x != nil && x.Private != nil {
		return *x.Private
	}
	return false
}

func (x *BackupTracking) GetMediaId() int64 {
	if x != nil && x.MediaId != nil {
		return *x.MediaId
	}
	return 0
}

var File_proto_mihon_backup_proto protoreflect.FileDescriptor

const file_proto_mihon_backup_proto_rawDesc = "" +
	"\n" +
	"\x18proto/mihon/backup.proto\x12\fmihon.backup\"C\n" +
	"\x0fPreferenceValue\x12\x12\n" +
	"\x04type\x18\x01 \x02(\tR\x04type\x12\x1c\n" +
	"\ttruevalue\x18\x02 \x02(\fR\ttruevalue\"\xd6\x03\n" +
	"\x06Backup\x12;\n" +
	"\vbackupManga\x18\x01 \x03(\v2\x19.mihon.backup.BackupMangaR\vbackupManga\x12H\n" +
	"\x10backupCategories\x18\x02 \x03(\v2\x1c.mihon.backup.BackupCategoryR\x10backupCategories\x12@\n" +
	"\rbackupSources\x18e \x03(\v2\x1a.mihon.backup.BackupSourceR\rbackupSources\x12L\n" +
	"\x11backupPreferences\x18h \x03(\v2\x1e.mihon.backup.BackupPreferenceR\x11backupPreferences\x12_\n" +
	"\x17backupSourcePreferences\x18i \x03(\v2%.mihon.backup.BackupSourcePreferencesR\x17backupSourcePreferences\x12T\n" +
	"\x13backupExtensionRepo\x18j \x03(\v2\".mihon.backup.BackupExtensionReposR\x13backupExtensionRepo\"`\n" +
	"\x0eBackupCategory\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x03R\x05order\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x14\n" +
	"\x05flags\x18d \x01(\x03R\x05flags\"\xef\x02\n" +
	"\rBackupChapter\x12\x10\n" +
	"\x03url\x18\x01 \x02(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\x12\x1c\n" +
	"\tscanlator\x18\x03 \x01(\tR\tscanlator\x12\x12\n" +
	"\x04read\x18\x04 \x01(\bR\x04read\x12\x1a\n" +
	"\bbookmark\x18\x05 \x01(\bR\bbookmark\x12\"\n" +
	"\flastPageRead\x18\x06 \x01(\x03R\flastPageRead\x12\x1c\n" +
	"\tdateFetch\x18\a \x01(\x03R\tdateFetch\x12\x1e\n" +
	"\n" +
	"dateUpload\x18\b \x01(\x03R\n" +
	"dateUpload\x12$\n" +
	"\rchapterNumber\x18\t \x01(\x02R\rchapterNumber\x12 \n" +
	"\vsourceOrder\x18\n" +
	" \x01(\x03R\vsourceOrder\x12&\n" +
	"\x0elastModifiedAt\x18\v \x01(\x03R\x0elastModifiedAt\x12\x18\n" +
	"\aversion\x18\f \x01(\x03R\aversion\"\xb2\x01\n" +
	"\x14BackupExtensionRepos\x12\x18\n" +
	"\abaseUrl\x18\x01 \x02(\tR\abaseUrl\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\x12\x1c\n" +
	"\tshortName\x18\x03 \x01(\tR\tshortName\x12\x18\n" +
	"\awebsite\x18\x04 \x02(\tR\awebsite\x124\n" +
	"\x15signingKeyFingerprint\x18\x05 \x02(\tR\x15signingKeyFingerprint\"a\n" +
	"\rBackupHistory\x12\x10\n" +
	"\x03url\x18\x01 \x02(\tR\x03url\x12\x1a\n" +
	"\blastRead\x18\x02 \x02(\x03R\blastRead\x12\"\n" +
	"\freadDuration\x18\x03 \x01(\x03R\freadDuration\"\xf4\x06\n" +
	"\vBackupManga\x12\x16\n" +
	"\x06source\x18\x01 \x02(\x03R\x06source\x12\x10\n" +
	"\x03url\x18\x02 \x02(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x04 \x01(\tR\x06artist\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x14\n" +
	"\x05genre\x18\a \x03(\tR\x05genre\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\"\n" +
	"\fthumbnailUrl\x18\t \x01(\tR\fthumbnailUrl\x12\x1c\n" +
	"\tdateAdded\x18\r \x01(\x03R\tdateAdded\x12\x16\n" +
	"\x06viewer\x18\x0e \x01(\x05R\x06viewer\x127\n" +
	"\bchapters\x18\x10 \x03(\v2\x1b.mihon.backup.BackupChapterR\bchapters\x12\x1e\n" +
	"\n" +
	"categories\x18\x11 \x03(\x03R\n" +
	"categories\x128\n" +
	"\btracking\x18\x12 \x03(\v2\x1c.mihon.backup.BackupTrackingR\btracking\x12\x1a\n" +
	"\bfavorite\x18d \x01(\bR\bfavorite\x12\"\n" +
	"\fchapterFlags\x18e \x01(\x05R\fchapterFlags\x12!\n" +
	"\fviewer_flags\x18g \x01(\x05R\vviewerFlags\x125\n" +
	"\ahistory\x18h \x03(\v2\x1b.mihon.backup.BackupHistoryR\ahistory\x12D\n" +
	"\x0eupdateStrategy\x18i \x01(\x0e2\x1c.mihon.backup.UpdateStrategyR\x0eupdateStrategy\x12&\n" +
	"\x0elastModifiedAt\x18j \x01(\x03R\x0elastModifiedAt\x12.\n" +
	"\x12favoriteModifiedAt\x18k \x01(\x03R\x12favoriteModifiedAt\x12.\n" +
	"\x12excludedScanlators\x18l \x03(\tR\x12excludedScanlators\x12\x18\n" +
	"\aversion\x18m \x01(\x03R\aversion\x12\x14\n" +
	"\x05notes\x18n \x01(\tR\x05notes\x12 \n" +
	"\vinitialized\x18o \x01(\bR\vinitialized\"Y\n" +
	"\x10BackupPreference\x12\x10\n" +
	"\x03key\x18\x01 \x02(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x02(\v2\x1d.mihon.backup.PreferenceValueR\x05value\"m\n" +
	"\x17BackupSourcePreferences\x12\x1c\n" +
	"\tsourceKey\x18\x01 \x02(\tR\tsourceKey\x124\n" +
	"\x05prefs\x18\x02 \x03(\v2\x1e.mihon.backup.BackupPreferenceR\x05prefs\"*\n" +
	"\x12IntPreferenceValue\x12\x14\n" +
	"\x05value\x18\x01 \x02(\x05R\x05value\"+\n" +
	"\x13LongPreferenceValue\x12\x14\n" +
	"\x05value\x18\x01 \x02(\x03R\x05value\",\n" +
	"\x14FloatPreferenceValue\x12\x14\n" +
	"\x05value\x18\x01 \x02(\x02R\x05value\"-\n" +
	"\x15StringPreferenceValue\x12\x14\n" +
	"\x05value\x18\x01 \x02(\tR\x05value\".\n" +
	"\x16BooleanPreferenceValue\x12\x14\n" +
	"\x05value\x18\x01 \x02(\bR\x05value\"0\n" +
	"\x18StringSetPreferenceValue\x12\x14\n" +
	"\x05value\x18\x01 \x03(\tR\x05value\">\n" +
	"\fBackupSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bsourceId\x18\x02 \x02(\x03R\bsourceId\"\xb2\x03\n" +
	"\x0eBackupTracking\x12\x16\n" +
	"\x06syncId\x18\x01 \x02(\x05R\x06syncId\x12\x1c\n" +
	"\tlibraryId\x18\x02 \x02(\x03R\tlibraryId\x12\x1e\n" +
	"\n" +
	"mediaIdInt\x18\x03 \x01(\x05R\n" +
	"mediaIdInt\x12 \n" +
	"\vtrackingUrl\x18\x04 \x01(\tR\vtrackingUrl\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12(\n" +
	"\x0flastChapterRead\x18\x06 \x01(\x02R\x0flastChapterRead\x12$\n" +
	"\rtotalChapters\x18\a \x01(\x05R\rtotalChapters\x12\x14\n" +
	"\x05score\x18\b \x01(\x02R\x05score\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12.\n" +
	"\x12startedReadingDate\x18\n" +
	" \x01(\x03R\x12startedReadingDate\x120\n" +
	"\x13finishedReadingDate\x18\v \x01(\x03R\x13finishedReadingDate\x12\x18\n" +
	"\aprivate\x18\f \x01(\bR\aprivate\x12\x18\n" +
	"\amediaId\x18d \x01(\x03R\amediaId*8\n" +
	"\x0eUpdateStrategy\x12\x11\n" +
	"\rALWAYS_UPDATE\x10\x00\x12\x13\n" +
	"\x0fONLY_FETCH_ONCE\x10\x01B)Z'github.com/galpt/mk-bkconv/pkg/mihon/pb"

var (
	file_proto_mihon_backup_proto_rawDescOnce sync.Once
	file_proto_mihon_backup_proto_rawDescData []byte
)

func file_proto_mihon_backup_proto_rawDescGZIP() []byte {
	file_proto_mihon_backup_proto_rawDescOnce.Do(func() {
		file_proto_mihon_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mihon_backup_proto_rawDesc), len(file_proto_mihon_backup_proto_rawDesc)))
	})
	return file_proto_mihon_backup_proto_rawDescData
}

var file_proto_mihon_backup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_mihon_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_mihon_backup_proto_goTypes = []any{
	(UpdateStrategy)(0),              // 0: mihon.backup.UpdateStrategy
	(*PreferenceValue)(nil),          // 1: mihon.backup.PreferenceValue
	(*Backup)(nil),                   // 2: mihon.backup.Backup
	(*BackupCategory)(nil),           // 3: mihon.backup.BackupCategory
	(*BackupChapter)(nil),            // 4: mihon.backup.BackupChapter
	(*BackupExtensionRepos)(nil),     // 5: mihon.backup.BackupExtensionRepos
	(*BackupHistory)(nil),            // 6: mihon.backup.BackupHistory
	(*BackupManga)(nil),              // 7: mihon.backup.BackupManga
	(*BackupPreference)(nil),         // 8: mihon.backup.BackupPreference
	(*BackupSourcePreferences)(nil),  // 9: mihon.backup.BackupSourcePreferences
	(*IntPreferenceValue)(nil),       // 10: mihon.backup.IntPreferenceValue
	(*LongPreferenceValue)(nil),      // 11: mihon.backup.LongPreferenceValue
	(*FloatPreferenceValue)(nil),     // 12: mihon.backup.FloatPreferenceValue
	(*StringPreferenceValue)(nil),    // 13: mihon.backup.StringPreferenceValue
	(*BooleanPreferenceValue)(nil),   // 14: mihon.backup.BooleanPreferenceValue
	(*StringSetPreferenceValue)(nil), // 15: mihon.backup.StringSetPreferenceValue
	(*BackupSource)(nil),             // 16: mihon.backup.BackupSource
	(*BackupTracking)(nil),           // 17: mihon.backup.BackupTracking
}
var file_proto_mihon_backup_proto_depIdxs = []int32{
	7,  // 0: mihon.backup.Backup.backupManga:type_name -> mihon.backup.BackupManga
	3,  // 1: mihon.backup.Backup.backupCategories:type_name -> mihon.backup.BackupCategory
	16, // 2: mihon.backup.Backup.backupSources:type_name -> mihon.backup.BackupSource
	8,  // 3: mihon.backup.Backup.backupPreferences:type_name -> mihon.backup.BackupPreference
	9,  // 4: mihon.backup.Backup.backupSourcePreferences:type_name -> mihon.backup.BackupSourcePreferences
	5,  // 5: mihon.backup.Backup.backupExtensionRepo:type_name -> mihon.backup.BackupExtensionRepos
	4,  // 6: mihon.backup.BackupManga.chapters:type_name -> mihon.backup.BackupChapter
	17, // 7: mihon.backup.BackupManga.tracking:type_name -> mihon.backup.BackupTracking
	6,  // 8: mihon.backup.BackupManga.history:type_name -> mihon.backup.BackupHistory
	0,  // 9: mihon.backup.BackupManga.updateStrategy:type_name -> mihon.backup.UpdateStrategy
	1,  // 10: mihon.backup.BackupPreference.value:type_name -> mihon.backup.PreferenceValue
	8,  // 11: mihon.backup.BackupSourcePreferences.prefs:type_name -> mihon.backup.BackupPreference
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_mihon_backup_proto_init() }
func file_proto_mihon_backup_proto_init() {
	if File_proto_mihon_backup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mihon_backup_proto_rawDesc), len(file_proto_mihon_backup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mihon_backup_proto_goTypes,
		DependencyIndexes: file_proto_mihon_backup_proto_depIdxs,
		EnumInfos:         file_proto_mihon_backup_proto_enumTypes,
		MessageInfos:      file_proto_mihon_backup_proto_msgTypes,
	}.Build()
	File_proto_mihon_backup_proto = out.File
	file_proto_mihon_backup_proto_goTypes = nil
	file_proto_mihon_backup_proto_depIdxs = nil
}
