// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/mihon/backup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Main backup message
type Backup struct {
	state                   protoimpl.MessageState     `protogen:"open.v1"`
	BackupManga             []*BackupManga             `protobuf:"bytes,1,rep,name=backupManga,proto3" json:"backupManga,omitempty"`
	BackupCategories        []*BackupCategory          `protobuf:"bytes,2,rep,name=backupCategories,proto3" json:"backupCategories,omitempty"`
	BackupSources           []*BackupSource            `protobuf:"bytes,101,rep,name=backupSources,proto3" json:"backupSources,omitempty"`
	BackupPreferences       []*BackupPreference        `protobuf:"bytes,104,rep,name=backupPreferences,proto3" json:"backupPreferences,omitempty"`
	BackupSourcePreferences []*BackupSourcePreferences `protobuf:"bytes,105,rep,name=backupSourcePreferences,proto3" json:"backupSourcePreferences,omitempty"`
	BackupExtensionRepo     []*BackupExtensionRepos    `protobuf:"bytes,106,rep,name=backupExtensionRepo,proto3" json:"backupExtensionRepo,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Backup) Reset() {
	*x = Backup{}
	mi := &file_proto_mihon_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backup) ProtoMessage() {}

func (x *Backup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backup.ProtoReflect.Descriptor instead.
func (*Backup) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{0}
}

func (x *Backup) GetBackupManga() []*BackupManga {
	if x != nil {
		return x.BackupManga
	}
	return nil
}

func (x *Backup) GetBackupCategories() []*BackupCategory {
	if x != nil {
		return x.BackupCategories
	}
	return nil
}

func (x *Backup) GetBackupSources() []*BackupSource {
	if x != nil {
		return x.BackupSources
	}
	return nil
}

func (x *Backup) GetBackupPreferences() []*BackupPreference {
	if x != nil {
		return x.BackupPreferences
	}
	return nil
}

func (x *Backup) GetBackupSourcePreferences() []*BackupSourcePreferences {
	if x != nil {
		return x.BackupSourcePreferences
	}
	return nil
}

func (x *Backup) GetBackupExtensionRepo() []*BackupExtensionRepos {
	if x != nil {
		return x.BackupExtensionRepo
	}
	return nil
}

// Manga entry with chapters, tracking, and history
type BackupManga struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Source             int64                  `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	Url                string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title              string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Artist             *string                `protobuf:"bytes,4,opt,name=artist,proto3,oneof" json:"artist,omitempty"`
	Author             *string                `protobuf:"bytes,5,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Description        *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Genre              []string               `protobuf:"bytes,7,rep,name=genre,proto3" json:"genre,omitempty"`
	Status             int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	ThumbnailUrl       *string                `protobuf:"bytes,9,opt,name=thumbnailUrl,proto3,oneof" json:"thumbnailUrl,omitempty"`
	DateAdded          int64                  `protobuf:"varint,13,opt,name=dateAdded,proto3" json:"dateAdded,omitempty"`
	Viewer             int32                  `protobuf:"varint,14,opt,name=viewer,proto3" json:"viewer,omitempty"`
	Chapters           []*BackupChapter       `protobuf:"bytes,16,rep,name=chapters,proto3" json:"chapters,omitempty"`
	Categories         []int64                `protobuf:"varint,17,rep,packed,name=categories,proto3" json:"categories,omitempty"`
	Tracking           []*BackupTracking      `protobuf:"bytes,18,rep,name=tracking,proto3" json:"tracking,omitempty"`
	Favorite           bool                   `protobuf:"varint,100,opt,name=favorite,proto3" json:"favorite,omitempty"`
	ChapterFlags       int32                  `protobuf:"varint,101,opt,name=chapterFlags,proto3" json:"chapterFlags,omitempty"`
	ViewerFlags        *int32                 `protobuf:"varint,103,opt,name=viewer_flags,json=viewerFlags,proto3,oneof" json:"viewer_flags,omitempty"`
	History            []*BackupHistory       `protobuf:"bytes,104,rep,name=history,proto3" json:"history,omitempty"`
	UpdateStrategy     int32                  `protobuf:"varint,105,opt,name=updateStrategy,proto3" json:"updateStrategy,omitempty"`
	LastModifiedAt     int64                  `protobuf:"varint,106,opt,name=lastModifiedAt,proto3" json:"lastModifiedAt,omitempty"`
	FavoriteModifiedAt *int64                 `protobuf:"varint,107,opt,name=favoriteModifiedAt,proto3,oneof" json:"favoriteModifiedAt,omitempty"`
	ExcludedScanlators []string               `protobuf:"bytes,108,rep,name=excludedScanlators,proto3" json:"excludedScanlators,omitempty"`
	Version            int64                  `protobuf:"varint,109,opt,name=version,proto3" json:"version,omitempty"`
	Notes              string                 `protobuf:"bytes,110,opt,name=notes,proto3" json:"notes,omitempty"`
	Initialized        bool                   `protobuf:"varint,111,opt,name=initialized,proto3" json:"initialized,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BackupManga) Reset() {
	*x = BackupManga{}
	mi := &file_proto_mihon_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupManga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupManga) ProtoMessage() {}

func (x *BackupManga) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupManga.ProtoReflect.Descriptor instead.
func (*BackupManga) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{1}
}

func (x *BackupManga) GetSource() int64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *BackupManga) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackupManga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BackupManga) GetArtist() string {
	if x != nil && x.Artist != nil {
		return *x.Artist
	}
	return ""
}

func (x *BackupManga) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *BackupManga) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *BackupManga) GetGenre() []string {
	if x != nil {
		return x.Genre
	}
	return nil
}

func (x *BackupManga) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BackupManga) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

func (x *BackupManga) GetDateAdded() int64 {
	if x != nil {
		return x.DateAdded
	}
	return 0
}

func (x *BackupManga) GetViewer() int32 {
	if x != nil {
		return x.Viewer
	}
	return 0
}

func (x *BackupManga) GetChapters() []*BackupChapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *BackupManga) GetCategories() []int64 {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *BackupManga) GetTracking() []*BackupTracking {
	if x != nil {
		return x.Tracking
	}
	return nil
}

func (x *BackupManga) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

func (x *BackupManga) GetChapterFlags() int32 {
	if x != nil {
		return x.ChapterFlags
	}
	return 0
}

func (x *BackupManga) GetViewerFlags() int32 {
	if x != nil && x.ViewerFlags != nil {
		return *x.ViewerFlags
	}
	return 0
}

func (x *BackupManga) GetHistory() []*BackupHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *BackupManga) GetUpdateStrategy() int32 {
	if x != nil {
		return x.UpdateStrategy
	}
	return 0
}

func (x *BackupManga) GetLastModifiedAt() int64 {
	if x != nil {
		return x.LastModifiedAt
	}
	return 0
}

func (x *BackupManga) GetFavoriteModifiedAt() int64 {
	if x != nil && x.FavoriteModifiedAt != nil {
		return *x.FavoriteModifiedAt
	}
	return 0
}

func (x *BackupManga) GetExcludedScanlators() []string {
	if x != nil {
		return x.ExcludedScanlators
	}
	return nil
}

func (x *BackupManga) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BackupManga) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *BackupManga) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

// Chapter information
type BackupChapter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Url            string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scanlator      *string                `protobuf:"bytes,3,opt,name=scanlator,proto3,oneof" json:"scanlator,omitempty"`
	Read           bool                   `protobuf:"varint,4,opt,name=read,proto3" json:"read,omitempty"`
	Bookmark       bool                   `protobuf:"varint,5,opt,name=bookmark,proto3" json:"bookmark,omitempty"`
	LastPageRead   int64                  `protobuf:"varint,6,opt,name=lastPageRead,proto3" json:"lastPageRead,omitempty"`
	DateFetch      int64                  `protobuf:"varint,7,opt,name=dateFetch,proto3" json:"dateFetch,omitempty"`
	DateUpload     int64                  `protobuf:"varint,8,opt,name=dateUpload,proto3" json:"dateUpload,omitempty"`
	ChapterNumber  float32                `protobuf:"fixed32,9,opt,name=chapterNumber,proto3" json:"chapterNumber,omitempty"`
	SourceOrder    int64                  `protobuf:"varint,10,opt,name=sourceOrder,proto3" json:"sourceOrder,omitempty"`
	LastModifiedAt int64                  `protobuf:"varint,11,opt,name=lastModifiedAt,proto3" json:"lastModifiedAt,omitempty"`
	Version        int64                  `protobuf:"varint,12,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackupChapter) Reset() {
	*x = BackupChapter{}
	mi := &file_proto_mihon_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupChapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupChapter) ProtoMessage() {}

func (x *BackupChapter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupChapter.ProtoReflect.Descriptor instead.
func (*BackupChapter) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{2}
}

func (x *BackupChapter) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackupChapter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupChapter) GetScanlator() string {
	if x != nil && x.Scanlator != nil {
		return *x.Scanlator
	}
	return ""
}

func (x *BackupChapter) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *BackupChapter) GetBookmark() bool {
	if x != nil {
		return x.Bookmark
	}
	return false
}

func (x *BackupChapter) GetLastPageRead() int64 {
	if x != nil {
		return x.LastPageRead
	}
	return 0
}

func (x *BackupChapter) GetDateFetch() int64 {
	if x != nil {
		return x.DateFetch
	}
	return 0
}

func (x *BackupChapter) GetDateUpload() int64 {
	if x != nil {
		return x.DateUpload
	}
	return 0
}

func (x *BackupChapter) GetChapterNumber() float32 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *BackupChapter) GetSourceOrder() int64 {
	if x != nil {
		return x.SourceOrder
	}
	return 0
}

func (x *BackupChapter) GetLastModifiedAt() int64 {
	if x != nil {
		return x.LastModifiedAt
	}
	return 0
}

func (x *BackupChapter) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Category
type BackupCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Order         int64                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Flags         int64                  `protobuf:"varint,100,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupCategory) Reset() {
	*x = BackupCategory{}
	mi := &file_proto_mihon_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupCategory) ProtoMessage() {}

func (x *BackupCategory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupCategory.ProtoReflect.Descriptor instead.
func (*BackupCategory) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{3}
}

func (x *BackupCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupCategory) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *BackupCategory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BackupCategory) GetFlags() int64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

// Tracking information
type BackupTracking struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SyncId    int32                  `protobuf:"varint,1,opt,name=syncId,proto3" json:"syncId,omitempty"`
	LibraryId int64                  `protobuf:"varint,2,opt,name=libraryId,proto3" json:"libraryId,omitempty"`
	// Deprecated: Marked as deprecated in proto/mihon/backup.proto.
	MediaIdInt          int32   `protobuf:"varint,3,opt,name=mediaIdInt,proto3" json:"mediaIdInt,omitempty"`
	TrackingUrl         string  `protobuf:"bytes,4,opt,name=trackingUrl,proto3" json:"trackingUrl,omitempty"`
	Title               string  `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	LastChapterRead     float32 `protobuf:"fixed32,6,opt,name=lastChapterRead,proto3" json:"lastChapterRead,omitempty"`
	TotalChapters       int32   `protobuf:"varint,7,opt,name=totalChapters,proto3" json:"totalChapters,omitempty"`
	Score               float32 `protobuf:"fixed32,8,opt,name=score,proto3" json:"score,omitempty"`
	Status              int32   `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	StartedReadingDate  int64   `protobuf:"varint,10,opt,name=startedReadingDate,proto3" json:"startedReadingDate,omitempty"`
	FinishedReadingDate int64   `protobuf:"varint,11,opt,name=finishedReadingDate,proto3" json:"finishedReadingDate,omitempty"`
	Private             bool    `protobuf:"varint,12,opt,name=private,proto3" json:"private,omitempty"`
	MediaId             int64   `protobuf:"varint,100,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BackupTracking) Reset() {
	*x = BackupTracking{}
	mi := &file_proto_mihon_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupTracking) ProtoMessage() {}

func (x *BackupTracking) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupTracking.ProtoReflect.Descriptor instead.
func (*BackupTracking) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{4}
}

func (x *BackupTracking) GetSyncId() int32 {
	if x != nil {
		return x.SyncId
	}
	return 0
}

func (x *BackupTracking) GetLibraryId() int64 {
	if x != nil {
		return x.LibraryId
	}
	return 0
}

// Deprecated: Marked as deprecated in proto/mihon/backup.proto.
func (x *BackupTracking) GetMediaIdInt() int32 {
	if x != nil {
		return x.MediaIdInt
	}
	return 0
}

func (x *BackupTracking) GetTrackingUrl() string {
	if x != nil {
		return x.TrackingUrl
	}
	return ""
}

func (x *BackupTracking) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BackupTracking) GetLastChapterRead() float32 {
	if x != nil {
		return x.LastChapterRead
	}
	return 0
}

func (x *BackupTracking) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *BackupTracking) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *BackupTracking) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BackupTracking) GetStartedReadingDate() int64 {
	if x != nil {
		return x.StartedReadingDate
	}
	return 0
}

func (x *BackupTracking) GetFinishedReadingDate() int64 {
	if x != nil {
		return x.FinishedReadingDate
	}
	return 0
}

func (x *BackupTracking) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *BackupTracking) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

// History entry
type BackupHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	LastRead      int64                  `protobuf:"varint,2,opt,name=lastRead,proto3" json:"lastRead,omitempty"`
	ReadDuration  int64                  `protobuf:"varint,3,opt,name=readDuration,proto3" json:"readDuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupHistory) Reset() {
	*x = BackupHistory{}
	mi := &file_proto_mihon_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupHistory) ProtoMessage() {}

func (x *BackupHistory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupHistory.ProtoReflect.Descriptor instead.
func (*BackupHistory) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{5}
}

func (x *BackupHistory) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackupHistory) GetLastRead() int64 {
	if x != nil {
		return x.LastRead
	}
	return 0
}

func (x *BackupHistory) GetReadDuration() int64 {
	if x != nil {
		return x.ReadDuration
	}
	return 0
}

// Source information
type BackupSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SourceId      int64                  `protobuf:"varint,2,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSource) Reset() {
	*x = BackupSource{}
	mi := &file_proto_mihon_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSource) ProtoMessage() {}

func (x *BackupSource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSource.ProtoReflect.Descriptor instead.
func (*BackupSource) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{6}
}

func (x *BackupSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupSource) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

// Preference entry
type BackupPreference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *PreferenceValue       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupPreference) Reset() {
	*x = BackupPreference{}
	mi := &file_proto_mihon_backup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupPreference) ProtoMessage() {}

func (x *BackupPreference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupPreference.ProtoReflect.Descriptor instead.
func (*BackupPreference) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{7}
}

func (x *BackupPreference) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BackupPreference) GetValue() *PreferenceValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// Source preferences
type BackupSourcePreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceKey     string                 `protobuf:"bytes,1,opt,name=sourceKey,proto3" json:"sourceKey,omitempty"`
	Prefs         []*BackupPreference    `protobuf:"bytes,2,rep,name=prefs,proto3" json:"prefs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSourcePreferences) Reset() {
	*x = BackupSourcePreferences{}
	mi := &file_proto_mihon_backup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSourcePreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSourcePreferences) ProtoMessage() {}

func (x *BackupSourcePreferences) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSourcePreferences.ProtoReflect.Descriptor instead.
func (*BackupSourcePreferences) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{8}
}

func (x *BackupSourcePreferences) GetSourceKey() string {
	if x != nil {
		return x.SourceKey
	}
	return ""
}

func (x *BackupSourcePreferences) GetPrefs() []*BackupPreference {
	if x != nil {
		return x.Prefs
	}
	return nil
}

// Extension repository
type BackupExtensionRepos struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl               string                 `protobuf:"bytes,1,opt,name=baseUrl,proto3" json:"baseUrl,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShortName             *string                `protobuf:"bytes,3,opt,name=shortName,proto3,oneof" json:"shortName,omitempty"`
	Website               string                 `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	SigningKeyFingerprint string                 `protobuf:"bytes,5,opt,name=signingKeyFingerprint,proto3" json:"signingKeyFingerprint,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BackupExtensionRepos) Reset() {
	*x = BackupExtensionRepos{}
	mi := &file_proto_mihon_backup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupExtensionRepos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupExtensionRepos) ProtoMessage() {}

func (x *BackupExtensionRepos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupExtensionRepos.ProtoReflect.Descriptor instead.
func (*BackupExtensionRepos) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{9}
}

func (x *BackupExtensionRepos) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *BackupExtensionRepos) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupExtensionRepos) GetShortName() string {
	if x != nil && x.ShortName != nil {
		return *x.ShortName
	}
	return ""
}

func (x *BackupExtensionRepos) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *BackupExtensionRepos) GetSigningKeyFingerprint() string {
	if x != nil {
		return x.SigningKeyFingerprint
	}
	return ""
}

// Preference value (sealed class representation)
type PreferenceValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*PreferenceValue_IntValue
	//	*PreferenceValue_LongValue
	//	*PreferenceValue_FloatValue
	//	*PreferenceValue_StringValue
	//	*PreferenceValue_BoolValue
	//	*PreferenceValue_StringSetValue
	Value         isPreferenceValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreferenceValue) Reset() {
	*x = PreferenceValue{}
	mi := &file_proto_mihon_backup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferenceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferenceValue) ProtoMessage() {}

func (x *PreferenceValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferenceValue.ProtoReflect.Descriptor instead.
func (*PreferenceValue) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{10}
}

func (x *PreferenceValue) GetValue() isPreferenceValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PreferenceValue) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*PreferenceValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *PreferenceValue) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*PreferenceValue_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *PreferenceValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*PreferenceValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *PreferenceValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*PreferenceValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *PreferenceValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*PreferenceValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *PreferenceValue) GetStringSetValue() *StringSet {
	if x != nil {
		if x, ok := x.Value.(*PreferenceValue_StringSetValue); ok {
			return x.StringSetValue
		}
	}
	return nil
}

type isPreferenceValue_Value interface {
	isPreferenceValue_Value()
}

type PreferenceValue_IntValue struct {
	IntValue int32 `protobuf:"varint,1,opt,name=intValue,proto3,oneof"`
}

type PreferenceValue_LongValue struct {
	LongValue int64 `protobuf:"varint,2,opt,name=longValue,proto3,oneof"`
}

type PreferenceValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,3,opt,name=floatValue,proto3,oneof"`
}

type PreferenceValue_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=stringValue,proto3,oneof"`
}

type PreferenceValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=boolValue,proto3,oneof"`
}

type PreferenceValue_StringSetValue struct {
	StringSetValue *StringSet `protobuf:"bytes,6,opt,name=stringSetValue,proto3,oneof"`
}

func (*PreferenceValue_IntValue) isPreferenceValue_Value() {}

func (*PreferenceValue_LongValue) isPreferenceValue_Value() {}

func (*PreferenceValue_FloatValue) isPreferenceValue_Value() {}

func (*PreferenceValue_StringValue) isPreferenceValue_Value() {}

func (*PreferenceValue_BoolValue) isPreferenceValue_Value() {}

func (*PreferenceValue_StringSetValue) isPreferenceValue_Value() {}

type StringSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringSet) Reset() {
	*x = StringSet{}
	mi := &file_proto_mihon_backup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringSet) ProtoMessage() {}

func (x *StringSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mihon_backup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringSet.ProtoReflect.Descriptor instead.
func (*StringSet) Descriptor() ([]byte, []int) {
	return file_proto_mihon_backup_proto_rawDescGZIP(), []int{11}
}

func (x *StringSet) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_proto_mihon_backup_proto protoreflect.FileDescriptor

const file_proto_mihon_backup_proto_rawDesc = "" +
	"\n" +
	"\x18proto/mihon/backup.proto\x12\fmihon.backup\"\xd6\x03\n" +
	"\x06Backup\x12;\n" +
	"\vbackupManga\x18\x01 \x03(\v2\x19.mihon.backup.BackupMangaR\vbackupManga\x12H\n" +
	"\x10backupCategories\x18\x02 \x03(\v2\x1c.mihon.backup.BackupCategoryR\x10backupCategories\x12@\n" +
	"\rbackupSources\x18e \x03(\v2\x1a.mihon.backup.BackupSourceR\rbackupSources\x12L\n" +
	"\x11backupPreferences\x18h \x03(\v2\x1e.mihon.backup.BackupPreferenceR\x11backupPreferences\x12_\n" +
	"\x17backupSourcePreferences\x18i \x03(\v2%.mihon.backup.BackupSourcePreferencesR\x17backupSourcePreferences\x12T\n" +
	"\x13backupExtensionRepo\x18j \x03(\v2\".mihon.backup.BackupExtensionReposR\x13backupExtensionRepo\"\xd3\a\n" +
	"\vBackupManga\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x03R\x06source\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\x06artist\x18\x04 \x01(\tH\x00R\x06artist\x88\x01\x01\x12\x1b\n" +
	"\x06author\x18\x05 \x01(\tH\x01R\x06author\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x14\n" +
	"\x05genre\x18\a \x03(\tR\x05genre\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12'\n" +
	"\fthumbnailUrl\x18\t \x01(\tH\x03R\fthumbnailUrl\x88\x01\x01\x12\x1c\n" +
	"\tdateAdded\x18\r \x01(\x03R\tdateAdded\x12\x16\n" +
	"\x06viewer\x18\x0e \x01(\x05R\x06viewer\x127\n" +
	"\bchapters\x18\x10 \x03(\v2\x1b.mihon.backup.BackupChapterR\bchapters\x12\x1e\n" +
	"\n" +
	"categories\x18\x11 \x03(\x03R\n" +
	"categories\x128\n" +
	"\btracking\x18\x12 \x03(\v2\x1c.mihon.backup.BackupTrackingR\btracking\x12\x1a\n" +
	"\bfavorite\x18d \x01(\bR\bfavorite\x12\"\n" +
	"\fchapterFlags\x18e \x01(\x05R\fchapterFlags\x12&\n" +
	"\fviewer_flags\x18g \x01(\x05H\x04R\vviewerFlags\x88\x01\x01\x125\n" +
	"\ahistory\x18h \x03(\v2\x1b.mihon.backup.BackupHistoryR\ahistory\x12&\n" +
	"\x0eupdateStrategy\x18i \x01(\x05R\x0eupdateStrategy\x12&\n" +
	"\x0elastModifiedAt\x18j \x01(\x03R\x0elastModifiedAt\x123\n" +
	"\x12favoriteModifiedAt\x18k \x01(\x03H\x05R\x12favoriteModifiedAt\x88\x01\x01\x12.\n" +
	"\x12excludedScanlators\x18l \x03(\tR\x12excludedScanlators\x12\x18\n" +
	"\aversion\x18m \x01(\x03R\aversion\x12\x14\n" +
	"\x05notes\x18n \x01(\tR\x05notes\x12 \n" +
	"\vinitialized\x18o \x01(\bR\vinitializedB\t\n" +
	"\a_artistB\t\n" +
	"\a_authorB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_thumbnailUrlB\x0f\n" +
	"\r_viewer_flagsB\x15\n" +
	"\x13_favoriteModifiedAt\"\x82\x03\n" +
	"\rBackupChapter\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\tscanlator\x18\x03 \x01(\tH\x00R\tscanlator\x88\x01\x01\x12\x12\n" +
	"\x04read\x18\x04 \x01(\bR\x04read\x12\x1a\n" +
	"\bbookmark\x18\x05 \x01(\bR\bbookmark\x12\"\n" +
	"\flastPageRead\x18\x06 \x01(\x03R\flastPageRead\x12\x1c\n" +
	"\tdateFetch\x18\a \x01(\x03R\tdateFetch\x12\x1e\n" +
	"\n" +
	"dateUpload\x18\b \x01(\x03R\n" +
	"dateUpload\x12$\n" +
	"\rchapterNumber\x18\t \x01(\x02R\rchapterNumber\x12 \n" +
	"\vsourceOrder\x18\n" +
	" \x01(\x03R\vsourceOrder\x12&\n" +
	"\x0elastModifiedAt\x18\v \x01(\x03R\x0elastModifiedAt\x12\x18\n" +
	"\aversion\x18\f \x01(\x03R\aversionB\f\n" +
	"\n" +
	"_scanlator\"`\n" +
	"\x0eBackupCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x03R\x05order\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x14\n" +
	"\x05flags\x18d \x01(\x03R\x05flags\"\xb6\x03\n" +
	"\x0eBackupTracking\x12\x16\n" +
	"\x06syncId\x18\x01 \x01(\x05R\x06syncId\x12\x1c\n" +
	"\tlibraryId\x18\x02 \x01(\x03R\tlibraryId\x12\"\n" +
	"\n" +
	"mediaIdInt\x18\x03 \x01(\x05B\x02\x18\x01R\n" +
	"mediaIdInt\x12 \n" +
	"\vtrackingUrl\x18\x04 \x01(\tR\vtrackingUrl\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12(\n" +
	"\x0flastChapterRead\x18\x06 \x01(\x02R\x0flastChapterRead\x12$\n" +
	"\rtotalChapters\x18\a \x01(\x05R\rtotalChapters\x12\x14\n" +
	"\x05score\x18\b \x01(\x02R\x05score\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12.\n" +
	"\x12startedReadingDate\x18\n" +
	" \x01(\x03R\x12startedReadingDate\x120\n" +
	"\x13finishedReadingDate\x18\v \x01(\x03R\x13finishedReadingDate\x12\x18\n" +
	"\aprivate\x18\f \x01(\bR\aprivate\x12\x18\n" +
	"\amediaId\x18d \x01(\x03R\amediaId\"a\n" +
	"\rBackupHistory\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\blastRead\x18\x02 \x01(\x03R\blastRead\x12\"\n" +
	"\freadDuration\x18\x03 \x01(\x03R\freadDuration\">\n" +
	"\fBackupSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bsourceId\x18\x02 \x01(\x03R\bsourceId\"Y\n" +
	"\x10BackupPreference\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.mihon.backup.PreferenceValueR\x05value\"m\n" +
	"\x17BackupSourcePreferences\x12\x1c\n" +
	"\tsourceKey\x18\x01 \x01(\tR\tsourceKey\x124\n" +
	"\x05prefs\x18\x02 \x03(\v2\x1e.mihon.backup.BackupPreferenceR\x05prefs\"\xc5\x01\n" +
	"\x14BackupExtensionRepos\x12\x18\n" +
	"\abaseUrl\x18\x01 \x01(\tR\abaseUrl\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\tshortName\x18\x03 \x01(\tH\x00R\tshortName\x88\x01\x01\x12\x18\n" +
	"\awebsite\x18\x04 \x01(\tR\awebsite\x124\n" +
	"\x15signingKeyFingerprint\x18\x05 \x01(\tR\x15signingKeyFingerprintB\f\n" +
	"\n" +
	"_shortName\"\x81\x02\n" +
	"\x0fPreferenceValue\x12\x1c\n" +
	"\bintValue\x18\x01 \x01(\x05H\x00R\bintValue\x12\x1e\n" +
	"\tlongValue\x18\x02 \x01(\x03H\x00R\tlongValue\x12 \n" +
	"\n" +
	"floatValue\x18\x03 \x01(\x02H\x00R\n" +
	"floatValue\x12\"\n" +
	"\vstringValue\x18\x04 \x01(\tH\x00R\vstringValue\x12\x1e\n" +
	"\tboolValue\x18\x05 \x01(\bH\x00R\tboolValue\x12A\n" +
	"\x0estringSetValue\x18\x06 \x01(\v2\x17.mihon.backup.StringSetH\x00R\x0estringSetValueB\a\n" +
	"\x05value\"#\n" +
	"\tStringSet\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06valuesB)Z'github.com/galpt/mk-bkconv/pkg/mihon/pbb\x06proto3"

var (
	file_proto_mihon_backup_proto_rawDescOnce sync.Once
	file_proto_mihon_backup_proto_rawDescData []byte
)

func file_proto_mihon_backup_proto_rawDescGZIP() []byte {
	file_proto_mihon_backup_proto_rawDescOnce.Do(func() {
		file_proto_mihon_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mihon_backup_proto_rawDesc), len(file_proto_mihon_backup_proto_rawDesc)))
	})
	return file_proto_mihon_backup_proto_rawDescData
}

var file_proto_mihon_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_mihon_backup_proto_goTypes = []any{
	(*Backup)(nil),                  // 0: mihon.backup.Backup
	(*BackupManga)(nil),             // 1: mihon.backup.BackupManga
	(*BackupChapter)(nil),           // 2: mihon.backup.BackupChapter
	(*BackupCategory)(nil),          // 3: mihon.backup.BackupCategory
	(*BackupTracking)(nil),          // 4: mihon.backup.BackupTracking
	(*BackupHistory)(nil),           // 5: mihon.backup.BackupHistory
	(*BackupSource)(nil),            // 6: mihon.backup.BackupSource
	(*BackupPreference)(nil),        // 7: mihon.backup.BackupPreference
	(*BackupSourcePreferences)(nil), // 8: mihon.backup.BackupSourcePreferences
	(*BackupExtensionRepos)(nil),    // 9: mihon.backup.BackupExtensionRepos
	(*PreferenceValue)(nil),         // 10: mihon.backup.PreferenceValue
	(*StringSet)(nil),               // 11: mihon.backup.StringSet
}
var file_proto_mihon_backup_proto_depIdxs = []int32{
	1,  // 0: mihon.backup.Backup.backupManga:type_name -> mihon.backup.BackupManga
	3,  // 1: mihon.backup.Backup.backupCategories:type_name -> mihon.backup.BackupCategory
	6,  // 2: mihon.backup.Backup.backupSources:type_name -> mihon.backup.BackupSource
	7,  // 3: mihon.backup.Backup.backupPreferences:type_name -> mihon.backup.BackupPreference
	8,  // 4: mihon.backup.Backup.backupSourcePreferences:type_name -> mihon.backup.BackupSourcePreferences
	9,  // 5: mihon.backup.Backup.backupExtensionRepo:type_name -> mihon.backup.BackupExtensionRepos
	2,  // 6: mihon.backup.BackupManga.chapters:type_name -> mihon.backup.BackupChapter
	4,  // 7: mihon.backup.BackupManga.tracking:type_name -> mihon.backup.BackupTracking
	5,  // 8: mihon.backup.BackupManga.history:type_name -> mihon.backup.BackupHistory
	10, // 9: mihon.backup.BackupPreference.value:type_name -> mihon.backup.PreferenceValue
	7,  // 10: mihon.backup.BackupSourcePreferences.prefs:type_name -> mihon.backup.BackupPreference
	11, // 11: mihon.backup.PreferenceValue.stringSetValue:type_name -> mihon.backup.StringSet
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_mihon_backup_proto_init() }
func file_proto_mihon_backup_proto_init() {
	if File_proto_mihon_backup_proto != nil {
		return
	}
	file_proto_mihon_backup_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_mihon_backup_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_mihon_backup_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_mihon_backup_proto_msgTypes[10].OneofWrappers = []any{
		(*PreferenceValue_IntValue)(nil),
		(*PreferenceValue_LongValue)(nil),
		(*PreferenceValue_FloatValue)(nil),
		(*PreferenceValue_StringValue)(nil),
		(*PreferenceValue_BoolValue)(nil),
		(*PreferenceValue_StringSetValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mihon_backup_proto_rawDesc), len(file_proto_mihon_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mihon_backup_proto_goTypes,
		DependencyIndexes: file_proto_mihon_backup_proto_depIdxs,
		MessageInfos:      file_proto_mihon_backup_proto_msgTypes,
	}.Build()
	File_proto_mihon_backup_proto = out.File
	file_proto_mihon_backup_proto_goTypes = nil
	file_proto_mihon_backup_proto_depIdxs = nil
}
